### ISSUE TITLE
Development installation fails

### ISSUE THREAD

**Issue by yagebu** [johannesjh/fava-desktop#2]
I tried installing it the development way, the first error was the following (I have poetry `1.0.10` installed):

```
The lock file might not be compatible with the current version of Poetry.
Upgrade Poetry to ensure the lock file is read properly or, alternatively, regenerate the lock file with the `poetry lock` command.
Installing dependencies from lock file

[NonExistentKey]
'Key "reference" does not exist.'
```

So I ran `poetry lock` and tried again. This started installing things but errored when trying to install and failing to build `pygobject==3.38.0`, which I already have installed system-wide.

**Comment by yagebu** [comment]
I actually managed to get it running by just installing it with `pip install .`, however this will still forcibly install the vendored Fava. Is there a way to tell poetry to use system-wide packages?

**Comment by johannesjh** [comment]
I renamed the project to fava-gtk and migrated this issue to https://github.com/johannesjh/fava-gtk/issues/2
